export const RESERVED_REALISTIC_CORPUS: string[] = [
  "The ticket clearly says Reserved, yet someone crossed it out.",
  'She whispered, "Reserved," and closed the velvet rope.',
  "On the chalkboard: RESERVED -- all caps, no explanation.",
  "The label read reserved; the tone felt less certain.",
  "He muttered '(Reserved)' under his breath and walked away.",
  "The footer ends with Reserved... then nothing else.",
  '"Is this seat Reserved?" she asked at 9:05 p.m.',
  "Please leave this row Reserved; guests arrive at 7.",
  "They stamped RESERVED. twice, once in red, once in blue.",
  "I found reserved! scribbled on a torn receipt.",
  'The sign says "Reserved" -- but the table is empty.',
  "At check-in, she typed Reserved: yes; paid: no.",
  "His note was odd: Reserved , with a space before the comma.",
  "The envelope had Reserved? written in pencil.",
  "We saw [Reserved] on the kiosk screen.",
  'The radio host read, "reserved," then paused for ads.',
  '"RESERVED" appeared in mixed text: ReSeRvEd on line two.',
  "Her planner lists: Mon - Reserved; Tue - open.",
  "He wrote Reserved/Confirmed, then erased Confirmed.",
  "The chatbot replied: reserved (temporary), retry later.",
  '"reserved." was all the email said.',
  "In the margin, someone added: *Reserved*.",
  "The gate display flashed RESERVED!!! for ten seconds.",
  "It was marked Reserved; however, nobody claimed it.",
  "The tiny print says reserved, reserved, reserved.",
  'She texted: "Reserved"... and then went offline.',
  "Agenda item 4 (Reserved) moved to next week.",
  "RESERVED? No -- actually, first come, first served.",
  "The card read 'Reserved,' in single quotes.",
  "He entered Reserved\\nand pressed submit too soon.",
  "First line: Reserved\\nSecond line: pending approval.",
  '"Reserved"  with two spaces after the quote looked wrong.',
  "Reserved\\tappeared after a tab in the imported text.",
  "The OCR output was reServed, not cleanly cased.",
  'I heard "Reserved..." over the speaker, crackly and clipped.',
  "File note -- Reserved (do not delete) -- was missing.",
  "She circled Reserved) without the opening parenthesis.",
  "The draft begins with (Reserved and never closes.",
  "Someone typed Reserved] where a parenthesis should be.",
  'The announcement read: RESERVED, then "delayed," then silence.',
  "The owner's stamp said Reserved's section is off-limits.",
  "\"Reserved's\" apostrophe made the editor wince.",
  "This isn't Reserved; it's preserved for winter.",
  "Their tone was unreserved, warm, and direct.",
  'Please reserve a booth, not a "Reserved" placard.',
  "The reservation ID was RES-104, unrelated to Reserved.",
  "We preserved the tape, but the label stayed reserved.",
  "An unreserved seat can become Reserved at boarding.",
  '"reserve" appears in lowercase, not the standalone target.',
  "The word reservation appears near Reserved, but means something else.",
  "He wrote PRESERVED in bold, then crossed out Reserved.",
  'The manual says "unreserved mode" for open seating.',
  "Her note read: reserve, reservation, reserved -- all different.",
  "They preserved, then re-preserved, the old theater posters.",
  "A RESERVED sign sat beside an unreserved queue.",
  '"Reserved," "preserved," and "reservation" were all in one paragraph.',
  "Do not confuse reserve with Reserved, she warned.",
  "At 11 a.m., RESERVED; at noon, unreserved.",
  "The caption says Reserved... while the metadata says reservation.",
  "Final fragment:\\nReserved\\npreserved\\nreserve.",
];
